#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          hrm_queuemanager
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The HRM Queue Manager daemon
### END INIT INFO
#
# This file is part of the Huygens Remote Manager
# Copyright and license notice: see license.txt

usage_exit() {
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
}

# exit on any error
set -e

# source the LSB init functions
. /lib/lsb/init-functions

# hrm.conf defines variable HRM_HOME
. /etc/hrm.conf

# global variables:
HRMD_PID="${HRM_LOG}/hrmd.pid"

start() {
    # start the service
    start_daemon -p $HRMD_PID "${HRM_HOME}/bin/hrm_queuemanager" --detach
}

stop() {
    # stop the service
    killproc -p $HRMD_PID "${HRM_HOME}/bin/hrm_queuemanager"
}

restart() {
    # stop and restart the service if the service is already running, otherwise
    # start the service
    stop
    start
}

force_reload() {
    # cause the configuration to be reloaded if the service supports this,
    # otherwise restart the service if it is running
    restart
}

status() {
    # print the current status of the service
    pidofproc -p $HRMD_PID "${HRM_HOME}/bin/hrm_queuemanager"
    status=$?
    if [ "$status" = 0 ]; then
        log_success_msg "$name is running"
        return 0
    elif [ "$status" = 4 ]; then
        log_failure_msg "could not access PID file for $name"
        return $status
    else
        log_failure_msg "$name is not running"
        return $status
    fi
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    force-reload)
        force_reload
        ;;
    status)
        status
        ;;
    *)
        usage_exit
        ;;
esac
