<?php
// This file is part of the Huygens Remote Manager
// Copyright and license notice: see license.txt

////////////////////////////////////////////////////////////////////////////////
//
//                           DO NOT EDIT THIS FILE!
//
////////////////////////////////////////////////////////////////////////////////

if (!isset($isServer)) {
    $isServer = false;
}

if ($isServer == true) {
    require_once(dirname(__FILE__) . "/../config/hrm_server_config.inc");
} else {
    require_once(dirname( __FILE__ ) . "/../config/hrm_client_config.inc");
}

// This is a hidden parameter for advanced users
if (!isset($userManager)) {
    // This default user manager script can be replaced in the configuration.
    // A demo server, for example, may use links to a demo directory instead of
    // creating an empty directory for each new user.
    $userManager = "bin/hrm";
}
?>
