<?php
// This file is part of the Huygens Remote Manager
// Copyright and license notice: see license.txt
//
// Author: Asheesh Gulati

echo '  
<table width="100%">
<tr>
<td width="100%" height="80" valign="top"><a href="http://www.fmi.ch/" target="_blank" ><img src="images/logomri1.jpg" height="80" hspace = "2.5"></a><img src="images/mri_logo.jpg" height="84" width="600" hspace = "2.5"></td>
</tr>
</table>'
?>

