<?php
// This file is part of the Huygens Remote Manager
// Copyright and license notice: see license.txt

require_once ("Parameter.inc.php");
require_once ("Database.inc.php");
require_once ("User.inc.php");
require_once ("hrm_config.inc.php");

/*!
  \class    Setting
  \brief    (Abstract) base class for all specific Setting classes
 */
abstract class Setting {
    
    /*!
      \var		$parameter
      \brief	Array of Parameter object
    */
    protected $parameter;

    /*!
      \var	$message
      \brief	Message for last invalid Parameter check
    */
    protected $message;

    /*!
      \var	$owner
      \brief	The User or Owner of the Setting
    */
    protected $owner;

    /*!
      \var	$name
      \brief	The name of the Setting
    */
    protected $name;

    /*!
      \var	$isDefault
      \brief	If true, the Setting is the default
    */
    protected $isDefault;

    /*!
      \var		$numberOfChannels
      \brief	Number of channels associated with the Setting
    */
    protected $numberOfChannels;

    /*!
      \brief	Protected constructor: creates an empty Setting
    */
    protected function __construct() {
        $this->parameter = array ();
        $this->isDefault = False;
    }

    /*!
      \brief	Returns the Parameter of given name
      \param	$name	Name of the Parameter to return
      \return	a Parameter object or NULL if the Parameter does not exist
    */
    public function parameter($name) {
        if (isset($this->parameter[$name])) {
            return $this->parameter[$name];
        } else {
            return NULL;
        }
    }

    /*!
      \brief	Sets a Parameter. The Parameter is stored in the Setting under 
              its name.
      \param	$parameter	A Parameter.
    */
    public function set($parameter) {
        $this->parameter[$parameter->name()] = $parameter;
    }

    /*!
      \brief  Returns the (error) message generated by last Parameter check
      \return	(error) message
    */
    public function message() {
        return $this->message;
    }

    /*!
      \brief	Return all Parameter names
      \return	array of parameter names
    */
    public function parameterNames() {
        $names = array();
        foreach ($this->parameter as $parameter) {
            $names[] = $parameter->name();
        }
        return $names;
    }

    /*!
      \brief	Returns the Owner of the Setting
      \return	Owner of the Setting
    */
    public function owner() {
        return $this->owner;
    }

    /*!
      \brief  Sets the Owner of the Setting
      \param  $owner	The owner of the Setting
    */
    public function setOwner( Owner $owner) {
        $this->owner = $owner;
    }

    /*!
      \brief	Returns the name of the Setting
      \return	name of the Setting
    */
    public function name() {
        return $this->name;
    }

    /*!
      \brief  Sets the name of the Setting
      \param  $name	Name of the Setting
    */
    public function setName($name) {
        $this->name = $name;
    }

    /*!
      \brief  Checks whether the Setting is the user's default setting
      \return	true if the Setting is the default Setting, false otherwise
    */
    public function isDefault() {
        return $this->isDefault;
    }

    /*!
      \brief  Sets current Setting as the default Setting for the user
    */
    public function beDefault() {
        $this->isDefault = True;
    }

    /*!
      \brief  Resets current Setting as no longer the default Setting for the user
    */
    public function resetDefault() {
        $this->isDefault = False;
    }

    /*!
      \brief  Copies the Parameter values from another Setting
      \param  $setting  The other Setting object from which the values are copied
    */
    public function copyParameterFrom($setting) {
        foreach ($setting->parameterNames() as $name) {
            $parameter = $this->parameter[$name];
            $otherParameter = $setting->parameter($name);
            $newValue = $otherParameter->internalValue();
            $parameter->setValue($newValue);
            $this->parameter[$name] = $parameter;
        }
    }

    /*!
      \brief	Returns the name of the database table in which the list of
              Setting names are stored.

      Besides the name, the table contains the Setting's name, owner and
      the standard (default) flag. This is an abstract function and must
      be reimplemented.
    */
    abstract function table();

    /*!
      \brief	Returns the name of the database table in which all the Parameters
              for the Settings stored in the table specified in table()

      This is an abstract function and must be reimplemented.
      \see table()
    */
    abstract function parameterTable();

    /*!
      \brief  Loads the Parameter values into current Setting
      \return	the loaded Setting
    */
    public function load() {
        $db = new DatabaseConnection();
        $result = $db->loadParameterSettings($this);
        if (!$result) {
            $this->message = "load setting - database access failed!";
        }
        return $result;
    }

    /*!
      \brief  Saves all Parameter values from current Setting to the database
      \return	true if saving was successul, false otherwise
    */
    public function save() {
        $db = new DatabaseConnection();

        $result = $db->saveParameterSettings($this);
        if (!$result) {
            $this->message = "save setting - database access failed!";
        }
        return $result;
    }

    /*!
      \brief	Sets the number of channels for the Setting

      All variable channels Parameter objects in the Setting will updated.

      \param	$channels	Number of channels (between 1 and 5)
    */
    public function setNumberOfChannels($channels) {
        $this->numberOfChannels = $channels;
        foreach ($this->parameter as $parameter) {
            if ($parameter->isVariableChannel()) {
                $parameter->setNumberOfChannels($this->numberOfChannels);
                $this->set($parameter);
            }
        }
    }

} // End of Setting class

/*
 ============================================================================
 */

/*!
  \class  ParameterSetting
  \brief	A ParameterSetting is a complete set of microscope, image and
            capture parameters
*/
class ParameterSetting extends Setting {

    /*!
      \brief	Constructor: constructs and initializes a ParameterSetting
    */
    public function __construct() {
        parent::__construct();
        $parameterClasses = array(
            'IsMultiChannel',
            'ImageFileFormat',
            'NumberOfChannels',
            'ImageGeometry',
            'MicroscopeType',
            'NumericalAperture',
            'ObjectiveMagnification',
            'ObjectiveType',
            'SampleMedium',
            'Binning',
            'ExcitationWavelength',
            'EmissionWavelength',
            'CMount',
            'TubeFactor',
            'CCDCaptorSize',
            'CCDCaptorSizeX',
            'ZStepSize',
            'TimeInterval',
            'PinholeSize',
            'PinholeSpacing',
            'PointSpreadFunction',
            'PSF',
            'CoverslipRelativePosition',
            'AberrationCorrectionNecessary',
            'PerformAberrationCorrection',
            'AberrationCorrectionMode',
            'AdvancedCorrectionOptions',
            'PSFGenerationDepth',
        );
        foreach ($parameterClasses as $class) {
            $param = new $class;
            $name = $param->name();
            $this->parameter[$name] = $param;
        }
    }

    /*!
      \brief	Returns the name of the database table in which the list of
      Setting names are stored.
    
      Besides the name, the table contains the Setting's name, owner and
      the standard (default) flag.
    */
    public function table() {
        return "parameter_setting";
    }

    /*!
      \brief	Returns the name of the database table in which all the Parameters
              for the Settings stored in the table specified in table()
      \see table()
    */
    public function parameterTable() {
        return "parameter";
    }

    /*!
      \brief	Checks that the posted Image Parameters are all defined
              and valid

      These Parameters must all be defined.

      \param	$postedParameters	The $_POST array
      \return	true if all Paraneters are defined and valid, false otherwise
    */
    public function checkPostedImageParameters($postedParameters) {

        if (count($postedParameters) == 0) {
            $this->message = '';
            return False;
        }

        $this->message = '';
        $noErrorsFound = True;

            // The file format must be defined
        if (isset($postedParameters["ImageFileFormat"])) {
                
            $parameter = $this->parameter("ImageFileFormat");
            $parameter->setValue($postedParameters["ImageFileFormat"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                return False;
            }
        }

        // The PSF type must be defined
        if (!isset($postedParameters["PointSpreadFunction"]) ||
                $postedParameters["PointSpreadFunction"] == "") {
            $this->message = "Please indicate whether you " .
                    "would like to calculate a theoretical PSF " .
                    "or use an existing measured one!";
            return False;
        } else {
            $parameter = $this->parameter("PointSpreadFunction");
            $parameter->setValue($postedParameters["PointSpreadFunction"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                return False;
            }
        }

        // The geometry must be defined for most file formats
        $singleParameters = $this->fixedGeometryFileFormats();
        if (!( array_search($postedParameters["ImageFileFormat"],
                $singleParameters) === false )) {
            $postedParameters["ImageGeometry"] = "XY - time";
        } elseif ($postedParameters["ImageFileFormat"] == 'tiff-series') {
            $postedParameters["ImageGeometry"] = "XYZ";
        } else {
            // We check that the value was posted
            if (!isset($postedParameters["ImageGeometry"]) ||
                    $postedParameters["ImageGeometry"] == "") {
                $this->message = "Please set the image geometry!";
                return False;
            }
        }
        $parameter = $this->parameter("ImageGeometry");
        $parameter->setValue($postedParameters["ImageGeometry"]);
        $this->set($parameter);
        if (!$parameter->check()) {
            $this->message = $parameter->message();
            return False;
        }

        // The number of channels must be defined for most file formats
        if ($postedParameters["ImageFileFormat"] == 'tiff-series') {
            $postedParameters["NumberOfChannels"] = "1";
        } else {
            // We check that the value was posted
            if (!isset($postedParameters["NumberOfChannels"]) ||
                    $postedParameters["NumberOfChannels"] == "") {
                $this->message = "Please set the number of channels!";
                return False;
            }
        }
        $parameter = $this->parameter("NumberOfChannels");
        $parameter->setValue($postedParameters["NumberOfChannels"]);
        $this->set($parameter);
        if (!$parameter->check()) {
            $this->message = $parameter->message();
            return False;
        }

        // All checked correctly, we can return success
        $this->message = "";
        return True;
    }

    /*!
      \brief	Checks that the posted Microscopy Parameters are all
              defined and valid

      These Parameter might have different confidence levels

      \param	$postedParameters	The $_POST array
      \return	true if all Paraneters are defined and valid, false otherwise
    */
    public function checkPostedMicroscopyParameters($postedParameters) {

        if (count($postedParameters) == 0) {
            $this->message = '';
            return False;
        }

        $this->message = '';
        $noErrorsFound = True;

        // Get the names of the relevant parameters
        $names = $this->microscopeParameterNames();

        // Small correction to the multi-channel names
        $names[array_search('ExcitationWavelength', $names)] =
            'ExcitationWavelength0';
        $names[array_search('EmissionWavelength', $names)] = 
            'EmissionWavelength0';

        // Check that the Parameters are set and contain valid values
        foreach ($names as $name) {

            // State of the Parameter and the submitted value(s)
            $valueSet = isset($postedParameters[$name]) &&
                    $postedParameters[$name] != '';

            // If the value is set, we check it no matter if it must be 
            // provided or not
            if ($valueSet) {

                // Handle particular parameters
                if ($name == 'ExcitationWavelength0') {
                    $value = array(null, null, null, null, null);
                    $value[0] = $postedParameters[$name];
                    for ($i = 1; $i < 5; $i++) {
                        if (isset($postedParameters["ExcitationWavelength$i"])) {
                            $value[$i] = 
                                $postedParameters["ExcitationWavelength$i"];
                        }
                    }
                    $name = 'ExcitationWavelength';
                } elseif ($name == 'EmissionWavelength0') {
                    $value = array(null, null, null, null, null);
                    $value[0] = $postedParameters[$name];
                    for ($i = 1; $i < 5; $i++) {
                        if (isset($postedParameters["EmissionWavelength$i"])) {
                            $value[$i] = 
                                $postedParameters["EmissionWavelength$i"];
                        }
                    }
                    $name = 'EmissionWavelength';
                } elseif ($name == "SampleMedium" &&
                        $postedParameters[$name] == "custom") {
                    if (isset($postedParameters['SampleMediumCustomValue'])) {
                        $value = $postedParameters['SampleMediumCustomValue'];
                    }
                } else {
                    $value = $postedParameters[$name];
                }

                // If the value is set we must check it (independent of the
                // $mustProvide flag)
                $parameter = $this->parameter($name);
                $parameter->setValue($value);
                $this->set($parameter);
                if (!$parameter->check()) {
                    $this->message = $parameter->message();
                    $noErrorsFound = False;
                }
            } else {

                // In this case it is important to know whether the Parameter
                // must have a value or not
                if ($name == "ExcitationWavelength0") {
                    $name = "ExcitationWavelength";
                } elseif ($name == "EmissionWavelength0") {
                    $name = "EmissionWavelength";
                }
                $parameter = $this->parameter($name);
                $mustProvide = $parameter->mustProvide();

                // Reset the Parameter
                $parameter->reset();
                $this->set($parameter);

                // If the Parameter value must be provided, we return an error
                if ($mustProvide) {

                    switch ($name) {
                        case "MicroscopeType" :
                            $this->message = 
                                "Please set the microscope type!";
                            break;
                        case "NumericalAperture" :
                            $this->message = 
                                "Please set the numerical aperture!";
                            break;
                        case "ObjectiveType" :
                            $this->message = 
                                "Please set the objective type!";
                            break;
                        case "SampleMedium" :
                            $this->message = 
                                "Please set the refractive index " .
                                    "of the sample medium!";
                            break;
                        case "ExcitationWavelength" :
                            $this->message = 
                                "Please set the excitation wavelength!";
                            break;
                        case "EmissionWavelength" :
                            $this->message = 
                                "Please set the emission wavelength!";
                            break;
                    }
                    $noErrorsFound = False;
                }
            }
        }
        return $noErrorsFound;
    }
    
    /*!
      \brief	Checks that the posted Capturing Parameters are all defined
              and valid
      \param	$postedParameters	The $_POST array
      \return	true if all Paraneters are defined and valid, false otherwise
    */

    public function checkPostedCapturingParameters($postedParameters) {

        if (count($postedParameters) == 0) {
            $this->message = '';
            return False;
        }

        $this->message = '';
        $noErrorsFound = True;

        // Here we test the Parameters explicitly
        // CCDCaptorSizeX
        $valueSet = isset($postedParameters["CCDCaptorSizeX"]) &&
                $postedParameters["CCDCaptorSizeX"] != '';

        $parameter = $this->parameter("CCDCaptorSizeX");

        if ($valueSet) {

            // Set the Parameter and check the value
            $parameter->setValue($postedParameters["CCDCaptorSizeX"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        } else {

            $mustProvide = $parameter->mustProvide();

            // Reset the Parameter
            $parameter->reset();
            $this->set($parameter);

            // If the Parameter value must be provided, we return an error
            if ($mustProvide) {
                $this->message = "Please set the pixel size!";
                $noErrorsFound = False;
            }
        }

        // ZStepSize must be defined for all 3D geometries
        if ($this->isThreeDimensional()) {

            $valueSet = isset($postedParameters["ZStepSize"]) &&
                    $postedParameters["ZStepSize"] != '';

            $parameter = $this->parameter("ZStepSize");

            if ($valueSet) {

                // Set the Parameter and check the value
                $parameter->setValue($postedParameters["ZStepSize"]);
                $this->set($parameter);
                if (!$parameter->check()) {
                    $this->message = $parameter->message();
                    $noErrorsFound = False;
                }
            } else {

                $mustProvide = $parameter->mustProvide();

                // Reset the Parameter
                $parameter->reset();
                $this->set($parameter);

                // If the Parameter value must be provided, we return an error
                if ($mustProvide) {
                    $this->message = "Please set the z-step!";
                    $noErrorsFound = False;
                }
            }
        }

        // TimeInterval must be defined for the XY-time and XYZ-time geometry
        if ($this->isTimeSeries()) {

            $valueSet = isset($postedParameters["TimeInterval"]) &&
                    $postedParameters["TimeInterval"] != '';

            $parameter = $this->parameter("TimeInterval");

            if ($valueSet) {

                // Set the Parameter and check the value
                $parameter->setValue($postedParameters["TimeInterval"]);
                $this->set($parameter);
                if (!$parameter->check()) {
                    $this->message = $parameter->message();
                    $noErrorsFound = False;
                }
            } else {

                $mustProvide = $parameter->mustProvide();

                // Reset the Parameter
                $parameter->reset();
                $this->set($parameter);

                // If the Parameter value must be provided, we return an error
                if ($mustProvide) {
                    $this->message = "Please set the time interval!";
                    $noErrorsFound = False;
                }
            }
        }

        // PinholeSize must be defined for all confocal microscopes
        if ($this->isMultiPointOrSinglePointConfocal()) {

            $valueSet = isset($postedParameters["PinholeSize0"]) &&
                    $postedParameters["PinholeSize0"] != '';

            $parameter = $this->parameter("PinholeSize");

            if ($valueSet) {

                // Set the Parameter and check the value
                $value = array(null, null, null, null, null);
                $value[0] = $postedParameters["PinholeSize0"];
                for ($i = 1; $i < 5; $i++) {
                    if (isset($postedParameters["PinholeSize$i"])) {
                        $value[$i] = $postedParameters["PinholeSize$i"];
                    }
                }
                $parameter->setValue($value);
                $this->set($parameter);
                if (!$parameter->check()) {
                    $this->message = $parameter->message();
                    $noErrorsFound = False;
                }
            } else {

                $mustProvide = $parameter->mustProvide();

                // Reset the Parameter
                $parameter->reset();
                $this->set($parameter);

                // If the Parameter value must be provided, we return an error
                if ($mustProvide) {
                    $this->message = "Please set the pinhole size!";
                    $noErrorsFound = False;
                }
            }
        }

        // PinholeSpacing must be defined for spinning disk confocals
        if ($this->isNipkowDisk()) {

            $valueSet = isset($postedParameters["PinholeSpacing"]) &&
                    $postedParameters["PinholeSpacing"] != '';

            $parameter = $this->parameter("PinholeSpacing");

            if ($valueSet) {

                // Set the Parameter and check the value
                $parameter->setValue($postedParameters["PinholeSpacing"]);
                $this->set($parameter);
                if (!$parameter->check()) {
                    $this->message = $parameter->message();
                    $noErrorsFound = False;
                }
            } else {

                $mustProvide = $parameter->mustProvide();

                // Reset the Parameter
                $parameter->reset();
                $this->set($parameter);

                // If the Parameter value must be provided, we return an error
                if ($mustProvide) {
                    $this->message = "Please set the pinhole spacing!";
                    $noErrorsFound = False;
                }
            }
        }

        return $noErrorsFound;
    }

    /*!
      \brief	Checks that the posted Aberration Correction Parameters are all 
              defined and valid
      \param	$postedParameters	The $_POST array
      \return	true if all Paraneters are defined and valid, false otherwise
    */
    public function checkPostedAberrationCorrectionParameters($postedParameters) {

        if (count($postedParameters) == 0) {
            $this->message = '';
            return False;
        }

        $this->message = '';
        $noErrorsFound = True;

        // PerformAberrationCorrection
        $valueSet = isset($postedParameters["PerformAberrationCorrection"]) &&
                $postedParameters["PerformAberrationCorrection"] != '';

        $parameter = $this->parameter("PerformAberrationCorrection");

        if ($valueSet) {

            // Set the Parameter and check the value
            $parameter->setValue($postedParameters["PerformAberrationCorrection"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        } else {

            $mustProvide = $parameter->mustProvide();

            // Reset the Parameter
            $parameter->reset();
            $this->set($parameter);

            // If the Parameter value must be provided, we return an error
            if ($mustProvide) {
                $this->message =
                    "Please choose whether to perform the correction!";
                $noErrorsFound = False;
            }
        }

        // CoverslipRelativePosition
        $valueSet = isset($postedParameters["CoverslipRelativePosition"]) &&
                $postedParameters["CoverslipRelativePosition"] != '';

        $parameter = $this->parameter("CoverslipRelativePosition");

        if ($valueSet) {

            // Set the Parameter and check the value
            $parameter->setValue($postedParameters["CoverslipRelativePosition"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        } else {

            $mustProvide = $parameter->mustProvide();

            // Reset the Parameter
            $parameter->reset();
            $this->set($parameter);

            // If the Parameter value must be provided, we return an error
            if ($mustProvide) {
                $this->message = 
                    "Please choose the relative coverslip position!";
                $noErrorsFound = False;
            }
        }

        // AberrationCorrectionMode
        $valueSet = isset($postedParameters["AberrationCorrectionMode"]) &&
                $postedParameters["AberrationCorrectionMode"] != '';

        $parameter = $this->parameter("AberrationCorrectionMode");

        if ($valueSet) {

            // Set the Parameter and check the value
            $parameter->setValue($postedParameters["AberrationCorrectionMode"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        } else {

            $mustProvide = $parameter->mustProvide();

            // Reset the Parameter
            $parameter->reset();
            $this->set($parameter);

            // If the Parameter value must be provided, we return an error
            if ($mustProvide) {
                $this->message = "Please set the aberration correction mode!";
                $noErrorsFound = False;
            }
        }

        // AdvancedCorrectionOptions
        $valueSet = isset($postedParameters["AdvancedCorrectionOptions"]) &&
                $postedParameters["AdvancedCorrectionOptions"] != '';

        $parameter = $this->parameter("AdvancedCorrectionOptions");

        if ($valueSet) {

            // Set the Parameter and check the value
            $parameter->setValue($postedParameters["AdvancedCorrectionOptions"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        } else {

            $mustProvide = $parameter->mustProvide();

            // Reset the Parameter
            $parameter->reset();
            $this->set($parameter);

            // If the Parameter value must be provided, we return an error
            if ($mustProvide) {
                $this->message = 
                    "Please indicate the options for the advanced correction!";
                $noErrorsFound = False;
            }
        }

        // The following Parameters may be defined depending on the values of
        // the previous one, but we will check them only if no errors have been
        // found so far
        if ($noErrorsFound == False) {
            return $noErrorsFound;
        }

        $parameter = $this->parameter("PerformAberrationCorrection");
        $perform = $parameter->value();
        $parameter = $this->parameter("AberrationCorrectionMode");
        $mode = $parameter->value();

        if ($perform == 1 && $mode == "advanced") {

            // PSFGenerationDepth
            $valueSet = isset($postedParameters["PSFGenerationDepth"]) &&
                    $postedParameters["PSFGenerationDepth"] != '';

            $parameter = $this->parameter("PSFGenerationDepth");

            if ($valueSet) {

                // Set the Parameter and check the value
                $parameter->setValue($postedParameters["PSFGenerationDepth"]);
                $this->set($parameter);
                if (!$parameter->check()) {
                    $this->message = $parameter->message();
                    $noErrorsFound = False;
                }
            } else {

                $mustProvide = $parameter->mustProvide();

                // Reset the Parameter
                $parameter->reset();
                $this->set($parameter);

                // If the Parameter value must be provided, we return an error
                if ($mustProvide) {
                    $this->message =
                        "Please indicate the depth for PSF generation!";
                    $noErrorsFound = False;
                }
            }
        }

        return $noErrorsFound;
    }

    /*!
      \brief	Checks that the posted Calculate Pixel Size Parameters are all defined
              and valid
      \param	$postedParameters	The $_POST array
      \return	true if all Paraneters are defined and valid, false otherwise
    */
    public function checkPostedCalculatePixelSizeParameters($postedParameters) {

        if (count($postedParameters) == 0) {
            $this->message = '';
            return False;
        }

        $this->message = '';
        $noErrorsFound = True;

        $names = $this->pixelSizeCalculationParameterNames();

        // Check that the Parameters are set and contain valid values
        foreach ($names as $name) {
            if (!isset($postedParameters[$name]) ||
                    $postedParameters[$name] == '') {
                // The Parameter is not set or empty, return an informative 
                // error message
                switch ($name) {
                    case "CCDCaptorSize" :
                        $this->message = "Please set the CCD pixel size!";
                        break;
                    case "Binning" :
                        $this->message = "Please set the binning!";
                        break;
                    case "NumberOfChannels" :
                        $this->message = "Please set CMount!";
                        break;
                    case "TubeFactor" :
                        $this->message = "Please set the tube factore!";
                        break;
                    case "ObjectiveMagnification" :
                        $this->message = 
                            "Please set the objective magnification!";
                        break;
                }
                $noErrorsFound = False;
            } else {
                // The Parameter is set, now check the value
                $parameter = $this->parameter($name);
                $parameter->setValue($postedParameters[$name]);
                $this->set($parameter);
                if (!$parameter->check()) {
                    $this->message = $parameter->message();
                    $noErrorsFound = False;
                }
            }
        }

        return $noErrorsFound;
    }

    /*!
      \brief	Returns the Parameter values needed for the aberration correction
      \return array with all Parameter values for the aberration correction. 
              The keys are the Parameter names
     */
    public function getAberractionCorrectionParameters() {
        $parameters = array(
            'AberrationCorrectionNecessary' => 
                $this->parameter('AberrationCorrectionNecessary')->value(),
            'PerformAberrationCorrection' => 
                $this->parameter('PerformAberrationCorrection')->value(),
            'CoverslipRelativePosition' => 
                $this->parameter('CoverslipRelativePosition')->value(),
            'AberrationCorrectionMode' => 
                $this->parameter('AberrationCorrectionMode')->value(),
            'AdvancedCorrectionOptions' => 
                $this->parameter('AdvancedCorrectionOptions')->value(),
            'PSFGenerationDepth' => 
                $this->parameter('PSFGenerationDepth')->value());
        return $parameters;
    }

    /*!
      \brief	Returns all Image Parameter names
      \return array of Image Parameter names
    */
    public function imageParameterNames() {
        $names = array();
        foreach ($this->parameter as $parameter) {
            if ($parameter->isForImage()) {
                $names[] = $parameter->name();
            }
        }
        
        return $names;
    }

    /*!
      \brief	Returns all Microscope Parameter names
      \return array of Microscope Parameter names
    */
    public function microscopeParameterNames() {
        $names = array();
        foreach ($this->parameter as $parameter) {
            if ($parameter->isForMicroscope()) {
                $names[] = $parameter->name();
            }
        }
        return $names;
    }

    /*!
      \brief	Returns all Capture Parameter names
      \return array of Capture Parameter names
     */
    public function capturingParameterNames() {
        $names = array();
        foreach ($this->parameter as $parameter) {
            if ($parameter->isForCapture()) {
                $names[] = $parameter->name();
            }
        }
        return $names;
    }

    /*!
      \brief	Returns all Correction Parameter names
      \return array of Correction Parameter names
    */
    public function correctionParameterNames() {
        $names = array();
        foreach ($this->parameter as $parameter) {
            if ($parameter->isForCorrection()) {
                $names[] = $parameter->name();
            }
        }
        return $names;
    }

    /*!
      \brief	Returns all Correction Parameter names
      \return array of Correction Parameter names
    */
    public function pixelSizeCalculationParameterNames() {
        $names = array();
        foreach ($this->parameter as $parameter) {
            if ($parameter->isForPixelSizeCalculation()) {
                $names[] = $parameter->name();
            }
        }
        return $names;
    }

    /*!
      \brief  Displays the setting as a text containing Parameter names and 
              their values
    */
    public function displayString() {
        $result = '';

        // These parameters are important to properly display all the others
        $numberOfChannels = $this->parameter("NumberOfChannels")->value();
        $PSFmode = $this->parameter("PointSpreadFunction")->value();
        $performAberrationCorrection = 
            $this->parameter("PerformAberrationCorrection")->value();
        $aberrationCorrectionMode = 
            $this->parameter("AberrationCorrectionMode")->value();
        $advancedCorrectionOptions = 
            $this->parameter("AdvancedCorrectionOptions")->value();

        // Not everything needs to be displayed, either because the Parameter
        // might be only internally used, or because it does not make sense for
        // the current Setting (e.g. it does not make sense to display the 
        // pinhole size if the microscope type is 'widefield'.
        foreach ($this->parameter as $parameter) {
            if (!$this->isMultiPointOrSinglePointConfocal() &&
                    $parameter->name() == 'PinholeSize')
                continue;
            if ($parameter->name() == 'IsMultiChannel')
                continue;
            if (!$this->isThreeDimensional() && 
                    $parameter->name() == 'ZStepSize')
                continue;
            if (!$this->isTimeSeries() && 
                    $parameter->name() == 'TimeInterval')
                continue;
            if (!$this->isNipkowDisk() && 
                    $parameter->name() == 'PinholeSpacing')
                continue;
            if ($parameter->name() == 'CMount') // This is obsolete
                continue;
            if ($parameter->name() == 'TubeFactor') // This is obsolete
                continue;
            if ($parameter->name() == 'ObjectiveMagnification') // This is obsolete
                continue;
            if ($parameter->name() == 'Binning') // This is obsolete
                continue;
            if ($parameter->name() == "AberrationCorrectionNecessary" &&
                    $PSFmode == 'measured')
                continue;
            if ($parameter->name() == 'CoverslipRelativePosition' &&
                    $PSFmode == 'measured')
                continue;
            if ($parameter->name() == 'PSF' && $PSFmode == 'theoretical')
                continue;
            if ($parameter->name() == 'CoverslipRelativePosition' &&
                    $performAberrationCorrection == 0)
                continue;
            if ($parameter->name() == 'AberrationCorrectionMode' &&
                    $performAberrationCorrection == 0)
                continue;
            if ($parameter->name() == 'AdvancedCorrectionOptions' &&
                    !( $performAberrationCorrection == 1 &&
                    $aberrationCorrectionMode == 'advanced' ))
                continue;
            if ($parameter->name() == 'PSFGenerationDepth' &&
                    !( $performAberrationCorrection == 1 &&
                    $aberrationCorrectionMode == 'advanced' &&
                    $advancedCorrectionOptions == 'user' ))
                continue;
            $result = $result . $parameter->displayString($numberOfChannels);
        }
        return $result;
    }

    /*!
      \brief	Asks HuCore to calculate the ideal (Nyquist) sampling rate
              for the current conditions.
      \return	an array with the ideal XY and Z sampling, or false if the sampling
              could not be calculated due to missing values
    */
    public function calculateNyquistRate() {
        // Use the most restrictive wavelength to compute the adaption
        $parameter = $this->parameter('EmissionWavelength');
        if ($this->isTwoPhoton()
                || $this->isMultiPointOrSinglePointConfocal()) {
            $parameter = $this->parameter('ExcitationWavelength');
        }
        $value = $parameter->value();
        $mostRestrictiveChannel = 0;
        $mostRestrictiveWavelength = $value[0];
        for ($i = 1; $i < $this->numberOfChannels(); $i++) {
            if ($value[$i] < $mostRestrictiveWavelength) {
                $mostRestrictiveChannel = $i;
                $mostRestrictiveWavelength = $value[$i];
            }
        }
        $parameter = $this->parameter('EmissionWavelength');
        $value = $parameter->value();
        $em = $value[$mostRestrictiveChannel];
        $parameter = $this->parameter('ExcitationWavelength');
        $value = $parameter->value();
        $ex = $value[$mostRestrictiveChannel];

        $parameter = $this->parameter('NumericalAperture');
        $na = (float) $parameter->value();

        $parameter = $this->parameter('MicroscopeType');
        $micr = $parameter->translatedValue();

        $parameter = $this->parameter('ObjectiveType');
        $ril = $parameter->translatedValue();

        if ($this->isTwoPhoton()) {
            $pcnt = 2;
        } else {
            $pcnt = 1;
        }
        // Only micr, na, em, ex and pcnt are necessary to calculate it.
        if ($micr == null || $na == null || $em == null ||
                $ex == null || $ril == null) {
            return false;
        }
        $opt = "-micr $micr -na $na -em $em -ex $ex -pcnt $pcnt -ril $ril";
        $ideal = askHuCore("calculateNyquistRate", $opt);
        // print_r($ideal);
        return array($ideal['xy'], $ideal['z']);
    }

    /*!
      \brief	Checks whether the chosen file format is multi channel
      \todo 	This is currently UNUSED!
      \return	true if multi channel, false otherwise
    */
    public function checkMultiChannelImageParameter() {
        $result = True;
        $parameter = $this->parameter('ImageFileFormat');
        $fileFormat = $parameter->value();
        if ((!in_array($fileFormat, $this->multiChannelFileFormats()))) {
            $this->message = "Please select a multichannel file format (" .
                    implode(", ", $this->multiChannelFileFormats()) . ")!";
            return False;
        }
        if (!in_array($fileFormat, $this->fixedGeometryFileFormats())) {
            $result = $this->checkGeometry('multi');
        }
        /*
          if (in_array($fileFormat, $this->variableChannelFileFormats())) {
          $result = $this->checkNumberOfChannels() && $result;
          }
         */
        return $result;
    }

    /*!
      \brief	Checks the Image Geometry (two or three dimensional, time series 
              or single image).
      \param	$prefix	Either 'single' (for single-channel geometries) or 'multi' 
              (for multi-channel geometries)
      \todo	This is currently UNUSED!
      \return	true if the geometry is valid, false otherwise
    */
    public function checkGeometry($prefix) {
        $result = True;
        $parameter = $this->parameter('ImageGeometry');
        $geometry = $parameter->internalValue();
        if ($geometry == '') {
            $geometry = '_';
        }
        $parts = explode('_', $geometry);
        $geometry = $parts[1];
        $prefix_ok = True;
        if ($prefix != $parts[0]) {
            $prefix_ok = False;
        }
        if (!$parameter->check() || !$prefix_ok) {
            $this->message = "Please select the image kind (" .
                    implode(", ", $parameter->possibleValues()) . ")!";
            return False;
        }
        return $result;
    }

    /*!
      \brief	Returns all 3-D geometries (i.e. 'XYZ', 'XYZ - time')
      \return	the 3D geometries
    */
    public function threeDimensionalGeometries() {
        static $threeDimensionalGeometries;
        if ($threeDimensionalGeometries == NULL) {
            $db = new DatabaseConnection();
            $threeDimensionalGeometries = $db->geometriesWith(True, NULL);
        }
        return $threeDimensionalGeometries;
    }

    /*!
      \brief	Returns all time series geometries (i.e. 'XY - time', 'XYZ - time')
      \return	the time series geometries
    */
    public function timeSeriesGeometries() {
        static $timeSeriesGeometries;
        if ($timeSeriesGeometries == NULL) {
            $db = new DatabaseConnection();
            $timeSeriesGeometries = $db->geometriesWith(NULL, True);
        }
        return $timeSeriesGeometries;
    }

    /*!
      \brief	Returns all fixed geometry file formats (i.e. those that are 2D)
      \return	the fixed geometry file formats
    */
    public function fixedGeometryFileFormats() {
        static $fixedGeometryFileFormats;
        if ($fixedGeometryFileFormats == NULL) {
            $db = new DatabaseConnection();
            $fixedGeometryFileFormats = $db->fileFormatsWith(NULL, NULL, True);
        }
        return $fixedGeometryFileFormats;
    }

    /*!
      \brief	Checks whether currently chosen file format has fixed geometry
      \return	true if the chosen file format has fixed geometry, false otherwise
    */
    public function isFixedGeometryFormat() {
        $param = $this->parameter('ImageFileFormat');
        $result = in_array($param->value(), $this->fixedGeometryFileFormats());
        return $result;
    }

    /*!
      \brief	Returns the file formats that support single channel images
      \return	array of file formats
    */
    public function singleChannelFileFormats() {
        static $singleChannelFileFormats;
        if ($singleChannelFileFormats == NULL) {
            $db = new DatabaseConnection();
            $singleChannelFileFormats = $db->fileFormatsWith(True, NULL, NULL);
        }
        return $singleChannelFileFormats;
    }

    /*!
      \brief	Returns the file formats that support multi-channel images
      \return	array of file formats
    */
    public function multiChannelFileFormats() {
        static $multiChannelFileFormats;
        if ($multiChannelFileFormats == NULL) {
            $db = new DatabaseConnection();
            $multiChannelFileFormats = $db->fileFormatsWith(False, NULL, NULL);
        }
        return $multiChannelFileFormats;
    }

    /*!
      \brief	Returns the file formats that support a variable number of channels
              per file
      \return	array of file formats
    */
    public function variableChannelFileFormats() {
        static $variableChannelFileFormats;
        if ($variableChannelFileFormats == NULL) {
            $db = new DatabaseConnection();
            $variableChannelFileFormats = 
                $db->fileFormatsWith(NULL, True, NULL);
        }
        return $variableChannelFileFormats;
    }

    /*!
      \brief	Checks whether current Setting is for multi-channel file formats
      \return	true if the number of channels set for current Setting is > 1,
              false otherwise
    */
    public function isMultiChannel() {
        $parameter = $this->parameter('NumberOfChannels');
        $num_channels = (int) $parameter->value();
        if ($num_channels > 1) {
            $result = True;
        } else {
            $result = False;
        }
        return $result;
    }

    /*!
      \brief	Checks whether currently selected file format is variable channel
      \return	true if the currently selected file format is variable channel
      \see variableChannelFileFormats()
    */
    function isVariableChannelFormat() {
        $result = False;
        $parameter = $this->parameter('ImageFileFormat');
        if (in_array($parameter->value(), $this->variableChannelFileFormats())) {
            $result = True;
        }
        return $result;
    }

    /*!
      \brief	Checks whether currently selected file format is one of the 
              TIFF variants
      \return	true if the currently selected file format is a TIFF variant
    */
    public function isTif() {
        $result = False;
        $parameter = $this->parameter('ImageFileFormat');
        if (strstr($parameter->value(), 'tif'))
            $result = True;
        return $result;
    }

    /*
      \brief	Returns the number of channels of the Setting
      \return	the number of channels
    */
    public function numberOfChannels() {
        $parameter = $this->parameter('NumberOfChannels');
        if ($parameter) {
            return ( (int) $parameter->value() );
        } else {
            return ( (int) 1 );
        }
    }

    /*!
      \brief	Checks whether the currently selected microscope type is spinning 
              (Nipkow) disk confocal
      \return	true if the currently selected microscope type is spinning (Nipkow) 
              disk, false otherwise
    */
    public function isNipkowDisk() {
        return $this->isMultiPointConfocal();
    }

    /*!
      \brief	Checks whether the currently selected microscope type is 2-Photon
      \return	true if the currently selected microscope type is 2-Photon, 
              false otherwise
    */
    public function isTwoPhoton() {
        $parameter = $this->parameter('MicroscopeType');
        $value = $parameter->value();
        return ($value == 'two photon');
    }

    /*!
      \brief	Checks whether the currently selected microscope type is 
              single-point confocal
      \return	true if the currently selected microscope type is single-point 
              confocal, false otherwise
    */
    public function isSinglePointConfocal() {
        $parameter = $this->parameter('MicroscopeType');
        $value = $parameter->value();
        return ($value == 'single point confocal');
    }

    /*!
      \brief	Checks whether the currently selected microscope type is spinning
              (Nipkow) disk confocal
      \return	true if the currently selected microscope type is spinning (Nipkow)
              disk, false otherwise
    */

    public function isMultiPointConfocal() {
        $parameter = $this->parameter('MicroscopeType');
        $value = $parameter->value();
        return ($value == 'multipoint confocal (spinning disk)');
    }

    /*!
      \brief	Checks whether the currently selected microscope type is widefield
      \return	true if the currently selected microscope type is widefield,
              false otherwise
    */
    public function isWidefield() {
        $parameter = $this->parameter('MicroscopeType');
        $value = $parameter->value();
        return ($value == 'widefield');
    }

    /*!
      \brief	Checks whether the currently selected microscope type is either 
              widefield of spinning disk
      \return	true if the currently selected microscope type is either widefield
              of spinning disk, false otherwise
    */
    public function isWidefieldOrMultiPoint() {
        return ($this->isWidefield() || $this->isMultiPointConfocal());
    }

    /*!
      \brief	Checks whether the currently selected microscope type is either 
              2-Photon or single-point confocal
      \return	true if the currently selected microscope type is either 2-Photon
              or single-point confocal, false otherwise
    */
    public function isTwoPhotonOrSinglePoint() {
        return ($this->isSinglePointConfocal() || $this->isTwoPhoton());
    }

    /*!
      \brief	Checks whether the currently selected microscope type is any type
              of confocal
      \return	true if the currently selected microscope type is any type of 
              confocal, false otherwise
    */
    public function isMultiPointOrSinglePointConfocal() {
        return ($this->isSinglePointConfocal() || 
                $this->isMultiPointConfocal());
    }

    /*!
      \brief	Checks that this Setting is for a 3D geometry and file format
      \return	true if both selected geometry and file format are 3D, 
              false otherwise
    */
    public function isThreeDimensional() {
        $parameter = $this->parameter('ImageGeometry');
        $value = $parameter->value();
        $format = $this->parameter('ImageFileFormat');
        $formatValue = $format->value();
        return (in_array($value, $this->threeDimensionalGeometries()) &&
                !in_array($formatValue, $this->fixedGeometryFileFormats()));
    }

    /*!
      \brief	Checks that this Setting is for a time series of images
      \return	true if both selected geometry and file format are for time series,
              false otherwise
    */
    public function isTimeSeries() {
        if ($this->isFixedGeometryFormat())
            return False;
        $parameter = $this->parameter('ImageGeometry');
        $value = $parameter->value();
        return (in_array($value, $this->timeSeriesGeometries()));
    }

    /*!
      \brief	Returns the pixel size (the value of CCDCaptorSizeX) in nm
      \todo	This is redundant!
      \return	pixel size in nm
    */
    public function pixelSize() {
        $param = $this->parameter('CCDCaptorSizeX');
        $size = (float) $param->value();
        return $size;
    }

    /*!
      \brief	Returns the sample size in X direction in um

      This is simply pixelSize() / 1000.

      \return	sample size in um
    */
    public function sampleSizeX() {
        $size = $this->pixelSize();
        return $size / 1000;
    }

    /*!
      \brief	Returns the sample size in Y direction in um

      This just returns the value in X direction.
      
      \return	sample size in um
    */
    public function sampleSizeY() {
        return $this->sampleSizeX();
    }

    /*!
      \brief	Returns the sample size in um in Z direction

      This is the value of the z-step size / 1000.

      \return	sample size in um
    */
    public function sampleSizeZ() {
        $param = $this->parameter('ZStepSize');
        $size = (float) $param->value();
        return $size / 1000;
    }

    /*!
      \brief	Returns the time interval between consecutive time points in a time
              series in seconds
      \return	time interval in seconds
    */
    public function sampleSizeT() {
        $param = $this->parameter('TimeInterval');
        $size = (float) $param->value();
        return $size / 1;
    }

}


/*
 ============================================================================
 */

/*!
  \class	TaskSetting
  \brief	A TaskSetting is a complete set of restoration parameters
*/
class TaskSetting extends Setting {

    /*!
      \var	$numberOfChannels
      \brief	Number of channels for the parameters of the TaskSetting
    */

    /*!
      \brief	Constructor: constructs and initializes a TaskSetting
    */
    public function TaskSetting() {
        parent::__construct();
        $parameterClasses = array(
            'SignalNoiseRatio',
            'BackgroundOffsetPercent',
            'NumberOfIterations',
            'OutputFileFormat',
            'MultiChannelOutput',
            'QualityChangeStoppingCriterion',
            'DeconvolutionAlgorithm' );

        foreach ($parameterClasses as $class) {
            $param = new $class;
            $name = $param->name();
            $this->parameter[$name] = $param;
            $this->numberOfChannels = NULL;
        }
    }

    /*!
      \brief	Returns the name of the database table in which the list of
              Setting names are stored.

      Besides the name, the table contains the Setting's name, owner and
      the standard (default) flag. This is an abstract function and must
      be reimplemented.
    */
    public function table() {
        return "task_setting";
    }

    /*!
      \brief	Returns the name of the database table in which all the Parameters
              for the Settings stored in the table specified in table()

      This is an abstract function and must be reimplemented.
    
      \see table()
    */
    public function parameterTable() {
        return "task_parameter";
    }

    /*!
      \brief	Checks that the posted Task Parameters are all defined
              and valid
      \param	$postedParameters	The $_POST array
    */
    public function checkPostedTaskParameters($postedParameters) {

        if (count($postedParameters) == 0) {
            $this->message = '';
            return False;
        }

        $this->message = '';
        $noErrorsFound = True;

        // Get the names of the relevant parameters
        $names = $this->taskParameterNames();

        // Deconvolution Algorithm - this should always be defined, but since
        // other parameters depend on it, in case it is not defined we return
        // here
        if (!isset($postedParameters["DeconvolutionAlgorithm"])) {
            $this->message = 'Please choose a deconvolution algorithm!';
            return False;
        }

        // Set the Parameter and check the value
        $parameter = $this->parameter("DeconvolutionAlgorithm");
        $parameter->setValue($postedParameters["DeconvolutionAlgorithm"]);
        $this->set($parameter);
        if (!$parameter->check()) {
            $this->message = 'Unknown deconvolution algorithm!';
            return False;
        }
        $algorithm = strtoupper($parameter->value());

        // Signal-To-Noise Ratio
        // Depending on the choice of the deconvolution algorithm, we will
        // check only the relevant entries
        $value = array(null, null, null, null, null);
        for ($i = 0; $i < 5; $i++) {
            $name = "SignalNoiseRatio" . $algorithm . "$i";
            if (isset($postedParameters[$name])) {
                $value[$i] = $postedParameters[$name];
            }
        }
        $parameter = $this->parameter("SignalNoiseRatio");
        $parameter->setValue($value);
        $this->set($parameter);
        if (!$parameter->check()) {
            $this->message = $parameter->message();
            $noErrorsFound = False;
        }

        // Background estimation
        if (!isset($postedParameters["BackgroundEstimationMode"]) ||
                $postedParameters["BackgroundEstimationMode"] == '') {
            $this->message = 'Please choose a background estimation mode!';
            $noErrorsFound = False;
        } else {
            $value = array(null, null, null, null, null);
            switch ($postedParameters["BackgroundEstimationMode"]) {
                case 'auto':

                    $value[0] = 'auto';
                    break;

                case 'object' :

                    $value[0] = 'object';
                    break;

                case 'manual' :

                    for ($i = 0; $i < 5; $i++) {
                        $name = "BackgroundOffsetPercent$i";
                        if (isset($postedParameters[$name])) {
                            $value[$i] = $postedParameters[$name];
                        }
                    }
                    break;

                default :
                    $this->message = 'Unknown background estimation mode!';
                    $noErrorsFound = False;
            }
            $parameter = $this->parameter("BackgroundOffsetPercent");
            $parameter->setValue($value);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        }

        // Number of iterations
        if (isset($postedParameters["NumberOfIterations"]) ||
                $postedParameters["NumberOfIterations"] == '') {
            $parameter = $this->parameter("NumberOfIterations");
            $parameter->setValue($postedParameters["NumberOfIterations"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        }

        // Quality change
        if (isset($postedParameters["QualityChangeStoppingCriterion"]) ||
                $postedParameters["QualityChangeStoppingCriterion"] == '') {
            $parameter = $this->parameter("QualityChangeStoppingCriterion");
            $parameter->setValue($postedParameters["QualityChangeStoppingCriterion"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        }

        return $noErrorsFound;
    }    

    /*!
      \brief	Returns all Task Parameter names
      \return array of Task Parameter names
    */
    public function taskParameterNames() {
        $names = array();
        foreach ($this->parameter as $parameter) {
            if ($parameter->isTaskParameter()) {
                $names[] = $parameter->name();
            }
        }
        return $names;
    }

    /*!
      \brief	Returns the number of channels of the Setting
      \return	the number of channels for the Setting
    */
    public function numberOfChannels() {
        return $this->numberOfChannels;
    }

    /* !
      \brief  Displays the setting as a text containing Parameter names 
              and their values
      \param	$numberOfChannels Number of channels (optional, default 
              value is 0)
     */
    public function displayString($numberOfChannels = 0) {
        $result = '';
        $algorithm = $this->parameter('DeconvolutionAlgorithm')->value();
        foreach ($this->parameter as $parameter) {
            if ($parameter->name() == 'SignalNoiseRatio') {
                $parameter->setAlgorithm($algorithm);
            }
            $result = $result . 
                $parameter->displayString($this->numberOfChannels());
        }
        return $result;
    }

    /*!
      \brief	Returns the TaskSetting as a text containing all parameters
              and their values. Only the parameter OutputFileFormat is left out.
   
      This is used for the web display where the output file format has
      not been choosen yet.
    
      \param	$numberOfChannels Number of channels (optional, default value is 0)
      \todo	Refactor!
    */
    public function displayStringWithoutOutputFileFormat($numberOfChannels = 0) {
        $parameter = $this->parameter('OutputFileFormat');
        $parameterList = $this->parameter;
        unset($parameterList['OutputFileFormat']);
        $this->parameter = $parameterList;
        $result = $this->displayString($numberOfChannels);
        $parameterList['OutputFileFormat'] = $parameter;
        $this->parameter = $parameterList;
        return $result;
    }

} // End of class taskSetting

/*
 ============================================================================
 */

/*!
  \class	AnalysisSetting
  \brief	An AnalysisSetting is a complete set of analysis parameters
*/
class AnalysisSetting extends Setting {

    /*!
      \var	$numberOfChannels
      \brief	Number of channels for the parameters of the TaskSetting
    */

    /*!
      \brief	Constructor: constructs and initializes an AnalysisSetting
    */
    public function AnalysisSetting() {
        parent::__construct();
        $parameterClasses = array(
            'ColocAnalysis',
            'ColocChannel',
            'ColocCoefficient',
            'ColocThreshold',
            'ColocMap',
        );

        foreach ($parameterClasses as $class) {
            $param = new $class;
            $name = $param->name();
            $this->parameter[$name] = $param;
            $this->numberOfChannels = NULL;
        }
    }

    /*!
      \brief	Returns the name of the database table in which the list of
              Setting names are stored.

      Besides the name, the table contains the Setting's name, owner and
      the standard (default) flag. This is an abstract function and must
      be reimplemented.
    */
    public function table() {
        return "analysis_setting";
    }

    /*!
      \brief	Returns the name of the database table in which all the Parameters
              for the Settings stored in the table specified in table()

      This is an abstract function and must be reimplemented.
    
      \see table()
    */
    public function parameterTable() {
        return "analysis_parameter";
    }
    
    /*!
      \brief	Checks that the posted analysis Parameters are all
                defined and valid
      \param	$postedParameters	The $_POST array
    */
    public function checkPostedAnalysisParameters($postedParameters) {
        if (count($postedParameters) == 0) {
            $this->message = '';
            return False;
        }

        $this->message = '';
        $noErrorsFound = True;
        
        $parameter = $this->parameter("ColocAnalysis");
        $parameter->setValue($postedParameters["ColocAnalysis"]);
        $this->set($parameter);

        if ($parameter->value() == False) {
            return $noErrorsFound;
        }

            // At least two channels must be selected.
        if (!isset($postedParameters["ColocChannel"])
            || $postedParameters["ColocChannel"] == "") {
            $this->message  = "Please indicate the channels (at least two) for ";
            $this->message .= "colocalization analysis.";
            return False;
        } else {
            $parameter = $this->parameter("ColocChannel");
            $parameter->setValue($postedParameters["ColocChannel"]);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                return False;
            }
        }

            // At least one coefficient must be selected.
        if (!isset($postedParameters["ColocCoefficient"])
            || $postedParameters["ColocCoefficient"] == "") {
            $this->message  = "Please indicate the coefficients for ";
            $this->message .= "colocalization analysis.";
            return False;
        } else {    
            $parameter = $this->parameter("ColocCoefficient");
            $parameter->setValue($postedParameters["ColocCoefficient"]);
            $this->set($parameter);
        }

          // Colocaliztion threshold mode
        if (!isset($postedParameters["ColocThresholdMode"]) ||
                $postedParameters["ColocThresholdMode"] == '') {
            $this->message = 'Please choose a colocalization threshold mode!';
            $noErrorsFound = False;
        } else {
            $value = array(null, null, null, null, null);
            switch ($postedParameters["ColocThresholdMode"]) {
                case 'auto':

                    $value[0] = 'auto';
                    break;
                    
                case 'manual' :

                    for ($i = 0; $i < 5; $i++) {
                        $name = "ColocThreshold$i";
                        if (isset($postedParameters[$name])) {
                            $value[$i] = $postedParameters[$name];
                        }
                    }
                    break;

                default :
                    $this->message = 'Unknown colocalization threshold mode!';
                    $noErrorsFound = False;
            }
            
            $parameter = $this->parameter("ColocThreshold");
            $parameter->setValue($value);
            $this->set($parameter);
            if (!$parameter->check()) {
                $this->message = $parameter->message();
                $noErrorsFound = False;
            }
        }
        
        $parameter = $this->parameter("ColocMap");
        $parameter->setValue($postedParameters["ColocMap"]);
        $this->set($parameter);
        
        return $noErrorsFound;
    }
    
    /*!
      \brief	Returns the number of channels of the Setting
      \return	the number of channels for the Setting
    */
    public function numberOfChannels() {
        return $this->numberOfChannels;
    }

    /* !
      \brief  Displays the setting as a text containing Parameter names 
              and their values
      \param	$numberOfChannels Number of channels (optional, default 
              value is 0)
     */
    public function displayString($numberOfChannels = 0) {
        $result = '';
        foreach ($this->parameter as $parameter) {
            $result = $result . 
                $parameter->displayString($this->numberOfChannels());
        }
        return $result;
    }

    /*!
      \brief	Returns the TaskSetting as a text containing all parameters
              and their values. Only the parameter OutputFileFormat is left out.
   
      This is used for the web display where the output file format has
      not been choosen yet.
    
      \param	$numberOfChannels Number of channels (optional, default value is 0)
      \todo	Refactor!
    */
    public function displayStringWithoutOutputFileFormat($numberOfChannels = 0) {
        $parameter = $this->parameter('OutputFileFormat');
        $parameterList = $this->parameter;
        unset($parameterList['OutputFileFormat']);
        $this->parameter = $parameterList;
        $result = $this->displayString($numberOfChannels);
        $parameterList['OutputFileFormat'] = $parameter;
        $this->parameter = $parameterList;
        return $result;
    }

} // End of class analysisSetting

/*
 ============================================================================
 */

/*!
  \class	JobParameterSetting
  \brief	A parameter setting is a complete set of microscope,
          image and capture parameters.

  A JobParameterSetting is a parameter setting that is used when a Job is
  executed by the queue manager. It uses different database tables and knows
  how to put its parameter settings onto a script.
*/
class JobParameterSetting extends ParameterSetting {

    /*!
      \brief	Returns the name of the database table in which the list of
              Setting names are stored.

      Besides the name, the table contains the Setting's name, owner and
      the standard (default) flag.
    */
    public function table() {
        return "job_parameter_setting";
    }

    /*!
      \brief	Returns the name of the database table in which all the Parameters
              for the Settings stored in the table specified in table()
      \see table()
    */
    public function parameterTable() {
        return "job_parameter";
    }

} // End of class JobParameterSetting

/*
 ============================================================================
 */

/*!
  \class	JobTaskSetting
  \brief	A job task setting is a complete set of restoration parameters that
          is used when a job is processed by the queue manager.
*/
class JobTaskSetting extends TaskSetting {

    /*!
      \brief	Returns the name of the database table in which the list of
              Setting names are stored.

      Besides the name, the table contains the Setting's name, owner and
      the standard (default) flag.
    */
    public function table() {
        return "job_task_setting";
    }

    /*!
      \brief	Returns the name of the database table in which all the Parameters
              for the Settings stored in the table specified in table()
      \see table()
    */
    public function parameterTable() {
        return "job_task_parameter";
    }

} // End of class JobTaskSetting

/*
 ============================================================================
 */

/*!
  \class	JobAnalysisSetting
  \brief	A job analysis setting is a complete set of analysis parameters
                that is used when a job is processed by the queue manager.
*/
class JobAnalysisSetting extends AnalysisSetting {

    /*!
      \brief	Returns the name of the database table in which the list of
              Setting names are stored.

      Besides the name, the table contains the Setting's name, owner and
      the standard (default) flag.
    */
    public function table() {
        return "job_analysis_setting";
    }

    /*!
      \brief	Returns the name of the database table in which all the Parameters
              for the Settings stored in the table specified in table()
      \see table()
    */
    public function parameterTable() {
        return "job_analysis";
    }

} // End of class JobAnalysisSetting
